apiVersion: v1
kind: PersistentVolume
metadata:
  name: iris-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/hp/kserve-models"   # Chemin local vers ton modèle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

