apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sk-model
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/hp/katib-iris-v3/v3/model
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sk-model
  namespace: kserve-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
