apiVersion: v1
kind: Pod
metadata:
  name: tmp-pvc-pod
  namespace: kubeflow
spec:
  containers:
    - name: pvc-container
      image: python:3.10-slim
      command: ["sleep", "3600"]
      volumeMounts:
        - name: model-volume
          mountPath: /model
  restartPolicy: Never
  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: katib-iris-models-pvc

